name: cfn-nag-sarif-action

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  
jobs:
  cfn-nag:
    name: Run cfn-nag scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run cfn-nag
        uses: stelligent/cfn-nag-sarif-action@master
        with:
          input_path: src